steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/translator-api/translator-app', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/translator-api/translator-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'translator-api'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/translator-api/translator-app'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--timeout'
    - '300s'
    - '--cpu'
    - '1'
    - '--memory'
    - '512Mi'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'FLASK_APP=app.main:app,FLASK_ENV=production,CORS_ALLOWED_ORIGINS=https://translator-api-843246270197.us-central1.run.app'
    - '--cpu-boost'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/translator-api/translator-app'